ecomprj/core/urls.py
from django.urls import path, include
from core.views import index, product_list_view, category_list_view, category_product_list_view, vendor_list_view, vendor_detail_view, product_detail_view, tag_list, ajax_add_review, search_view, filter_product, checkout_view, add_to_cart, cart_view, delete_item_from_cart, update_from_cart, payment_completed_view, payment_failed_view

app_name = 'core'

urlpatterns = [
    # Define the URL pattern for the index view
    path("", index, name="index"),
    path("products/", product_list_view, name="product-list"),
    path("products/<pid>/", product_detail_view, name="product-detail"),

    # Category

    path("category/", category_list_view, name="category-list"),
    path("category/<cid>/", category_product_list_view, name="category-product-list"),

    # Vendor

    path("vendor/", vendor_list_view, name="vendor-list"),
    path("vendor/<str:vid>/", vendor_detail_view, name="vendor-detail"),

    # Tags

    path("products/tag/<slug:tag_slug>/", tag_list, name="tags"),

    # Add Reviews url

    path('ajax-add-review/<int:pid>/', ajax_add_review, name='ajax-add-review'),
    # path("ajax-add-review/<int:pid>/", ajax_add_review, name="ajax-add-review"),

    # Search
    path("search/", search_view, name="search"),

    # Filter products
    path("filter-products/", filter_product, name="filter-products"),

    # Add to Cart
    path("add-to-cart/", add_to_cart, name="add-to-cart"),
    path("cart/", cart_view, name="cart"),

    # Delete Items from Cart
    path("delete-from-cart/", delete_item_from_cart, name="delete-from-cart"),

    # Update Items from Cart
    path("update-cart/", update_from_cart, name="update-cart"),


    # CheckOut
    path("checkout/", checkout_view, name="checkout"),

    # PayPal Url
    path('paypal/', include('paypal.standard.ipn.urls')),

    # Payment Succesful
    path("payment-completed/", payment_completed_view, name="payment-completed"),

    # Payment Succesful
    path("payment-failed/", payment_failed_view, name="payment-failed"),




]

ecomprj/ecomprj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # Admin site URL
    path('admin/', admin.site.urls),

    # Include URL patterns from the "core" app
    path("", include("core.urls")),
    path("user/", include("userauths.urls")),
    path("ckeditor/", include("ckeditor_uploader.urls")),
]


# If in DEBUG mode, serve static and media files through Django
if settings.DEBUG:
    # Serve static files
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # Serve media files
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecomprj/core/forms.py
from django import forms
from core.models import ProductReview

class ProductReviewForm(forms.ModelForm):
    review = forms.CharField(widget=forms.Textarea(attrs={'placeholder': 'Write Review'}))

    class Meta:
        model = ProductReview
        fields = ['review', 'rating']

ecomprj/core/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse

from core.models import Product, Category, Vendor, CartOrder, CartOrderItems, ProductImages, ProductReview, Wishlist, Address
from django.shortcuts import render, get_object_or_404
from django.db.models import Count, Avg, Q
from taggit.models import Tag
from core.forms import ProductReviewForm
from django.template.loader import render_to_string
from django.contrib import messages

from django.urls import reverse
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
from paypal.standard.forms import PayPalPaymentsForm
from django.contrib.auth.decorators import login_required


# Create your views here.

def index(request):

    # products = Product.objects.all().order_by("-id")
    products = Product.objects.filter(product_status="published", featured=True)

    context = {
        "products":products
    }

    return render(request, 'core/index.html', context)



def product_list_view(request):

    products = Product.objects.filter(product_status="published")



    context = {
        "products":products,
    }

    return render(request, 'core/product-list.html', context)

def category_list_view(request):

    categories = Category.objects.all()

    context = {
        "categories":categories
    }
    return render(request, 'core/category-list.html', context)

def category_product_list_view(request, cid):
    category = Category.objects.get(cid=cid)
    products = Product.objects.filter(product_status="published", category=category)

    context = {
        "category":category,
        "products":products,
    }
    return render(request, 'core/category-product-list.html', context)


def vendor_list_view(request):
    vendors = Vendor.objects.all()
    context = {
        "vendors":vendors
    }
    return render(request, "core/vendor-list.html", context)

def vendor_detail_view(request, vid):
    vendor = Vendor.objects.get(vid=vid)
    products = Product.objects.filter(vendor=vendor, product_status="published")
    context = {
        "vendor":vendor,
        "products":products,
    }
    return render(request, "core/vendor-detail.html", context)

def product_detail_view(request, pid):

    product = Product.objects.get(pid=pid)

    # Or you can use this code to get an object too , first import the get_objects_or_404

    # then you say product = get_objects_or_404(Product, pid=pid)
    products = Product.objects.filter(category=product.category).exclude(pid=pid)
    # This code retrieves the products that are in the same category with the product
                               # OR
    # products = Product.objects.filter(category=product.category).exclude(pid=pid)[:10]
    # This is to get the first 10 related posts

    # Getting All Reviews related to a product
    reviews = ProductReview.objects.filter(product=product).order_by("-date")

     # Getting All Average Reviews
    average_rating = ProductReview.objects.filter(product=product).aggregate(rating=Avg('rating'))

    # Products review form

    review_form = ProductReviewForm

    make_review = True
    if request.user.is_authenticated:
        user_review_count = ProductReview.objects.filter(user=request.user, product=product).count()
        if user_review_count > 0:
            make_review = False

    p_image = product.p_images.all()

    context = {
        "p":product,
        "p_image":p_image,
        "make_review":  make_review,
        "review_form":  review_form,
        "average_rating":average_rating,
        "reviews":reviews,
        "products":products,
    }
    return render(request, "core/product-detail.html", context)

def tag_list(request, tag_slug=None):
    products = Product.objects.filter(product_status="published").order_by("-id")
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        products = products.filter(tags__in=[tag])

    context = {
        "products":products,
        "tag":tag,
    }
    return render(request, "core/tag.html", context)


def ajax_add_review(request, pid):

    # Retrieve the product using the provided product ID (pid)
    product = Product.objects.get(pk=pid)

    # Get the currently logged-in user from the request
    user = request.user

    # Create a new ProductReview object and save it to the database
    review = ProductReview.objects.create(
        user = user,
        product = product,
        review = request.POST['review'],
        rating = request.POST['rating'],
    )

    context = {
        'user': user.username,
        'review': request.POST['review'],
        'rating': request.POST['rating'],
    }

    # Calculate the average rating for the product's reviews
    average_reviews = ProductReview.objects.filter(product=product).aggregate(rating=Avg('rating'))

    return JsonResponse(
       {
            'bool': True,
            'context':context,
            'average_reviews' : average_reviews,
       }
    )

# def search_view(request):
#     # query = request.Get['q'] Or
#     query = request.GET.get('q')
#     products = Product.objects.filter(title__icontains=query, description__icontains=query).order_by("-date")

#     # We can use Startith when we want to search a product with first letters but Icontain will seacr base on the letters
#     # xample of Icontain, Imegine searching for Bitter Kola and we have Biter Lemon in the database, If we search "Bitter" Bitter Lemon will come out bkus we have Bitter in waht we are searhing

#     context = {
#         "products": products,
#         "query": query,
#     }

#     return render(request, "core/search.html", context)

def search_view(request):
    # query = request.Get['q'] Or
    query = request.GET.get("q")
    products = Product.objects.filter(Q(title__icontains=query)|Q(description__icontains=query)).order_by("-date")

    # We can use Startswith when we want to search a product with the first letters, but Icontains will search based on the letters.
    # Example of Icontains: Imagine searching for Bitter Kola, and we have Biter Lemon in the database. If we search "Bitter," Bitter Lemon will come out because we have "Bitter" in what we are searching.

    context = {
        "products": products,
        "query": query,
    }

    return render(request, "core/search.html", context)

def filter_product(request):
    categories = request.GET.getlist('category[]')
    vendors = request.GET.getlist('vendor[]')

    min_price = request.GET['min_price']
    max_price = request.GET['max_price']

    products = Product.objects.filter(product_status="published").order_by("-id").distinct()

    products = products.filter(price__gte=min_price)
    products = products.filter(price__lte=max_price)

    if len(categories) > 0:
        products = products.filter(category__id__in=categories).distinct()

    if len(vendors) > 0:
        vendors = products.filter(vendor__id__in=vendors).distinct()

    # context = {
    #     "products": products
    # }


    data = render_to_string("core/async/product-list.html", {"products": products})

    return JsonResponse({"data": data})


def add_to_cart(request):
    # Initialize an empty dictionary to store product information for the current request
    cart_product = {}

    # Extract product information from the request's GET parameters and store it in the cart_product dictionary
    cart_product[str(request.GET['id'])] = {
        'title': request.GET['title'],
        'qty': request.GET['qty'],
        'price': request.GET['price'],
        'image': request.GET['image'],
        'pid': request.GET['pid'],
    }

    # Check if 'cart_data_obj' is already in the user's session
    if 'cart_data_obj' in request.session:

    # Check if the current product ID is already in the cart
        if str(request.GET['id']) in request.session['cart_data_obj']:
            cart_data = request.session['cart_data_obj']
            cart_data[str(request.GET['id'])]['qty'] = int(cart_product[str(request.GET['id'])]['qty'])
            cart_data.update(cart_data)
            request.session['cart_data_obj'] = cart_data

        else:
            # If the product is not in the cart, add it to the existing cart data
            cart_data = request.session['cart_data_obj']
            cart_data.update(cart_product)
            request.session['cart_data_obj'] = cart_data

    else:
        # If there is no cart data in the session, initialize it with the current product
        request.session['cart_data_obj'] = cart_product
    # Return a JSON response containing the updated cart data and the total number of items in the cart
    return JsonResponse({"data":request.session['cart_data_obj'], 'totalcartitems': len(request.session['cart_data_obj'])})


def cart_view(request):
    cart_total_amount = 0
    if "cart_data_obj" in request.session:
        for p_id, item in request.session['cart_data_obj'].items():
           cart_total_amount += int(item['qty']) * float(item['price'])
        return render(request, "core/cart.html", {"cart_data":request.session['cart_data_obj'], 'totalcartitems': len(request.session['cart_data_obj']), 'cart_total_amount': cart_total_amount})
    else:
        messages.warning(request, "Your Cart Is Empty")
        return redirect("core:index")
        # return render(request, "core/cart.html",  {"cart_data":"", 'totalcartitems': len(request.session['cart_data_obj']), 'cart_total_amount': cart_total_amount})



def delete_item_from_cart(request):
    product_id = str(request.GET['id'])
    if 'cart_data_obj' in request.session:
        if product_id in request.session['cart_data_obj']:
            cart_data = request.session['cart_data_obj']
            del request.session['cart_data_obj'][product_id]
            request.session['cart_data_obj'] = cart_data

    cart_total_amount = 0
    if "cart_data_obj" in request.session:
        for p_id, item in request.session['cart_data_obj'].items():

ecomprj/templates/core/category-list.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content %}

    <main class="main">
        <div class="page-header mt-30 mb-75">
            <div class="container">
                <div class="archive-header">
                    <div class="row align-items-center">
                        <div class="col-xl-3">
                            <h1 class="mb-15">Categories</h1>
                            <div class="breadcrumb">
                                <a href="index.html" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                                <span></span> Categories
                            </div>
                        </div>
                        <!-- <div class="col-xl-9 text-end d-none d-xl-block">
                            <ul class="tags-list">
                                <li class="hover-up">
                                    <a href="blog-category-grid.html"><i class="fi-rs-cross mr-10"></i>Shopping</a>
                                </li>
                                <li class="hover-up active">
                                    <a href="blog-category-grid.html"><i class="fi-rs-cross mr-10"></i>Recips</a>
                                </li>
                                <li class="hover-up">
                                    <a href="blog-category-grid.html"><i class="fi-rs-cross mr-10"></i>Kitchen</a>
                                </li>
                                <li class="hover-up">
                                    <a href="blog-category-grid.html"><i class="fi-rs-cross mr-10"></i>News</a>
                                </li>
                                <li class="hover-up mr-0">
                                    <a href="blog-category-grid.html"><i class="fi-rs-cross mr-10"></i>Food</a>
                                </li>
                            </ul>
                        </div> -->
                    </div>
                </div>
            </div>
        </div>
        <div class="page-content mb-50">
            <div class="container">
                <div class="row">
                    <div class="col-lg-9">
                        <div class="shop-product-fillter mb-50 pr-30">
                            <div class="totall-product">
                                <h2>
                                    <img class="w-36px mr-10" src="assets/imgs/theme/icons/category-1.svg" alt="" />
                                    {{categories.count}} Categories
                                </h2>
                            </div>
                            <div class="sort-by-product-area">
                                <div class="sort-by-cover mr-10">
                                    <div class="sort-by-product-wrap">
                                        <div class="sort-by">
                                            <span><i class="fi-rs-apps"></i>Show:</span>
                                        </div>
                                        <div class="sort-by-dropdown-wrap">
                                            <span> 50 <i class="fi-rs-angle-small-down"></i></span>
                                        </div>
                                    </div>
                                    <div class="sort-by-dropdown">
                                        <ul>
                                            <li><a class="active" href="#">50</a></li>
                                            <li><a href="#">100</a></li>
                                            <li><a href="#">150</a></li>
                                            <li><a href="#">200</a></li>
                                            <li><a href="#">All</a></li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="sort-by-cover">
                                    <div class="sort-by-product-wrap">
                                        <div class="sort-by">
                                            <span><i class="fi-rs-apps-sort"></i>Sort:</span>
                                        </div>
                                        <div class="sort-by-dropdown-wrap">
                                            <span>Featured <i class="fi-rs-angle-small-down"></i></span>
                                        </div>
                                    </div>
                                    <div class="sort-by-dropdown">
                                        <ul>
                                            <li><a class="active" href="#">Featured</a></li>
                                            <li><a href="#">Newest</a></li>
                                            <li><a href="#">Most comments</a></li>
                                            <li><a href="#">Release Date</a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="hello">

                        </div>
                        <div class="loop-grid pr-30">
                            <div class="row">
                                {% for c in categories %}
                                <article class="col-xl-4 col-lg-6 col-md-6 text-center hover-up mb-30 animated">
                                    <div class="post-thumb">
                                        <a href="{% url 'core:category-product-list' c.cid %}">
                                        {% comment %} <a href="blog-post-right.html"> {% endcomment %}

                                            <img class="border-radius-15" src="{{c.image.url}}" alt="" />
                                        </a>
                                        <div class="entry-meta">
                                            <a class="entry-meta meta-2" href="blog-category-grid.html"><i class="fi-rs-heart"></i></a>
                                        </div>
                                    </div>
                                    <div class="entry-content-2">
                                    {% comment %} <h6 class="mb-10 font-sm"><a class="entry-meta text-muted" href="blog-category-grid.html">Side Dish</a></h6> {% endcomment %}
                                        <h4 class="post-title mb-15">
                                             {% comment %} <a href="{% url 'core:category-product-list' c.cid %}"> {% endcomment %}
                                            <a href="{% url 'core:category-product-list' c.cid %}">{{ c.title }}</a>
                                        </h4>
                                        <div class="entry-meta font-xs color-grey mt-10 pb-10">
                                            <div>
                                                <span class="hit-count mr-10">{{c.category.count}} Product{{c.category.count|pluralize}}</span>
                                            </div>
                                        </div>
                                    </div>
                                </article>
                                {% endfor %}
                            </div>
                        </div>
                        <!-- <div class="pagination-area mt-15 mb-sm-5 mb-lg-0">
                            <nav aria-label="Page navigation example">
                                <ul class="pagination justify-content-start">
                                    <li class="page-item">
                                        <a class="page-link" href="#"><i class="fi-rs-arrow-small-left"></i></a>
                                    </li>
                                    <li class="page-item"><a class="page-link" href="#">1</a></li>
                                    <li class="page-item active"><a class="page-link" href="#">2</a></li>
                                    <li class="page-item"><a class="page-link" href="#">3</a></li>
                                    <li class="page-item"><a class="page-link dot" href="#">...</a></li>
                                    <li class="page-item"><a class="page-link" href="#">6</a></li>
                                    <li class="page-item">
                                        <a class="page-link" href="#"><i class="fi-rs-arrow-small-right"></i></a>
                                    </li>
                                </ul>
                            </nav>
                        </div> -->
                    </div>
                    <div class="col-lg-3 primary-sidebar sticky-sidebar">
                        <div class="widget-area">
                            <div class="sidebar-widget-2 widget_search mb-50">
                                <div class="search-form">
                                    <form action="#">
                                        <input type="text" placeholder="Search…" />
                                        <button type="submit"><i class="fi-rs-search"></i></button>
                                    </form>
                                </div>
                            </div>
                            <div class="sidebar-widget widget-category-2 mb-50">
                                <h5 class="section-title style-1 mb-30">Category</h5>
                                <ul>
                                    {% for c in categories %}
                                    <li>
                                        {% comment %} <a href="{% url 'core:category-product-list' c.cid %}"> <img src="{{c.image.url}}" alt="" />{{c.title}}</a><span class="count">{{c.category.count}}</span> {% endcomment %}
                                    </li>
                                    {% endfor %}
                                </ul>
                            </div>


                            <div class="banner-img wow fadeIn mb-50 animated d-lg-block d-none">
                                <img src="assets/imgs/banner/banner-11.png" alt="" />
                                <div class="banner-text">
                                    <span>Oganic</span>
                                    <h4>
                                        Save 17% <br />
                                        on <span class="text-brand">Oganic</span><br />
                                        Juice
                                    </h4>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>

{% endblock content %}

ecomprj/templates/core/checkout.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content %}
    <main class="main">
        <div class="page-header breadcrumb-wrap">
            <div class="container">
                <div class="breadcrumb">
                    <a href="index.html" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                    <span></span> Shop
                    <span></span> Checkout
                </div>
            </div>
        </div>
        <div class="container mb-80 mt-50">
            <div class="row">
                <div class="col-lg-8 mb-40">
                    <h1 class="heading-2 mb-10">Checkout</h1>
                    <div class="d-flex justify-content-between">
                        <h6 class="text-body">There are <span class="text-brand">{{ totalcartitems }}</span> products in your cart</h6>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-7">
                    <div class="row mb-50">

                        <div class="col-lg-6">
                            <form method="post" class="apply-coupon">
                                <input type="text" placeholder="Enter Coupon Code...">
                                <button class="btn  btn-md" name="login">Apply Coupon</button>
                            </form>
                        </div>
                    </div>
                    <div class="row">
                        <h4 class="mb-30">Billing Details</h4>
                        <form method="post">
                            <div class="row">
                                <div class="form-group col-lg-6">
                                    <input type="text" required="" name="fname" value="{{ request.user.username|title }}" placeholder="First name *">
                                </div>
                                <div class="form-group col-lg-6">
                                    <input type="text" required="" name="lname" placeholder="mobile *" value="{{ active_address.mobile }}">
                                </div>
                            </div>
                            <div class="row">
                                <div class="form-group col-lg-6">
                                    <input type="text" name="billing_address" value="{{ active_address.address }}" required="" placeholder="Address *">
                                </div>

                            </div>

                        </form>
                    </div>
                </div>
                <div class="col-lg-5">
                    <div class="border p-40 cart-totals ml-30 mb-50">
                        <div class="d-flex align-items-end justify-content-between mb-30">
                            <h4>Your Order</h4>
                            <h6 class="text-muted">Subtotal - <span class="text-brand">${{cart_total_amount|floatformat:2}}</span></h6>

                        </div>
                        <div class="divider-2 mb-30"></div>
                        {% comment %} <a href="{% url 'core:cart' %}" class="btn btn-fill-out btn-block mt-30 mb-40">Go back to Cart</a> {% endcomment %}

                        <div class="table-responsive order_table checkout">
                            <table class="table no-border">
                                <tbody>
                                    {% for product_id, item in cart_data.items %}
                                    <tr>
                                        <td class="image product-thumbnail"><img src="{{ item.image }}" alt="#"></td>
                                        <td>
                                            <h6 class="w-160 mb-5"><a href="{% url 'core:product-detail' item.pid %}" class="text-heading">{{item.title}}</a></h6></span>

                                        </td>
                                        <td>
                                            <h6 class="text-muted pl-20 pr-20">x {{ item.qty }}</h6>
                                        </td>
                                        <td>
                                            <h5 class="text-muted">${{item.price}}</h5>
                                        </td>

                                        <td>
                                            <h5 class="text-brand">${% widthratio item.price 1 item.qty %}</h5>
                                        </td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="payment ml-30">
                        <h4 class="mb-30">Payment</h4>
                        <div class="payment_option">
                            <div class="custome-radio">
                                <input class="form-check-input" required="" type="radio" name="payment_option" id="exampleRadios3" checked="">
                                <label class="form-check-label" for="exampleRadios3" data-bs-toggle="collapse" data-target="#bankTranfer" aria-controls="bankTranfer">Direct Bank Transfer</label>
                            </div>
                            <div class="custome-radio">
                                <input class="form-check-input" required="" type="radio" name="payment_option" id="exampleRadios4" checked="">
                                <label class="form-check-label" for="exampleRadios4" data-bs-toggle="collapse" data-target="#checkPayment" aria-controls="checkPayment">Cash on delivery</label>
                            </div>
                            <div class="custome-radio">
                                <input class="form-check-input" required="" type="radio" name="payment_option" id="exampleRadios5" checked="">
                                <label class="form-check-label" for="exampleRadios5" data-bs-toggle="collapse" data-target="#paypal" aria-controls="paypal">Online Getway</label>
                            </div>
                        </div>
                        <div class="payment-logo d-flex">
                            <img class="mr-15" src="{% static 'assets/imgs/theme/icons/payment-paypal.svg' %}" alt="">
                            <img class="mr-15" src="{% static 'assets/imgs/theme/icons/payment-visa.svg' %}" alt="">
                            <img class="mr-15" src="{% static 'assets/imgs/theme/icons/payment-master.svg' %}" alt="">
                            <img src="{% static 'assets/imgs/theme/icons/payment-zapper.svg' %}" alt="">
                        </div>
                        <div class="w-50">
                            {{paypal_payment_button.render}}
                        </div>

                        <!-- <a href="#" class="btn btn-fill-out btn-block mt-30">Place an Order<i class="fi-rs-sign-out ml-15"></i></a> -->
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock content %}