ecomprj/core/urls.py
from django.urls import path, include
from core.views import index, product_list_view, category_list_view, category_product_list_view, vendor_list_view, vendor_detail_view, product_detail_view, tag_list, ajax_add_review, search_view, filter_product, checkout_view, add_to_cart, cart_view, delete_item_from_cart, update_from_cart, payment_completed_view, payment_failed_view

app_name = 'core'

urlpatterns = [
    # Define the URL pattern for the index view
    path("", index, name="index"),
    path("products/", product_list_view, name="product-list"),
    path("products/<pid>/", product_detail_view, name="product-detail"),

    # Category

    path("category/", category_list_view, name="category-list"),
    path("category/<cid>/", category_product_list_view, name="category-product-list"),

    # Vendor

    path("vendor/", vendor_list_view, name="vendor-list"),
    path("vendor/<str:vid>/", vendor_detail_view, name="vendor-detail"),

    # Tags

    path("products/tag/<slug:tag_slug>/", tag_list, name="tags"),

    # Add Reviews url

    path('ajax-add-review/<int:pid>/', ajax_add_review, name='ajax-add-review'),
    # path("ajax-add-review/<int:pid>/", ajax_add_review, name="ajax-add-review"),

    # Search
    path("search/", search_view, name="search"),

    # Filter products
    path("filter-products/", filter_product, name="filter-products"),

    # Add to Cart
    path("add-to-cart/", add_to_cart, name="add-to-cart"),
    path("cart/", cart_view, name="cart"),

    # Delete Items from Cart
    path("delete-from-cart/", delete_item_from_cart, name="delete-from-cart"),

    # Update Items from Cart
    path("update-cart/", update_from_cart, name="update-cart"),


    # CheckOut
    path("checkout/", checkout_view, name="checkout"),

    # PayPal Url
    path('paypal/', include('paypal.standard.ipn.urls')),

    # Payment Succesful
    path("payment-completed/", payment_completed_view, name="payment-completed"),

    # Payment Succesful
    path("payment-failed/", payment_failed_view, name="payment-failed"),




]

ecomprj/ecomprj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # Admin site URL
    path('admin/', admin.site.urls),

    # Include URL patterns from the "core" app
    path("", include("core.urls")),
    path("user/", include("userauths.urls")),
    path("ckeditor/", include("ckeditor_uploader.urls")),
]


# If in DEBUG mode, serve static and media files through Django
if settings.DEBUG:
    # Serve static files
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # Serve media files
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecomprj/core/models.py
from pyexpat import model
from email.policy import default
from django.db import models
from shortuuid.django_fields import ShortUUIDField
from django.utils.html import mark_safe

from userauths.models import User
from taggit.managers import TaggableManager
from ckeditor_uploader.fields import RichTextUploadingField


def user_directory_path(instance, filename):
    return 'user_{0}/{1}'.format(instance.user.id, filename)

# Create your models here.

STATUS_CHOICE = (
    ("process", "processing"),
    ("shipped", "Shipped"),
    ("delivered", "Delivered"),
)

STATUS = (

    ("draft", "Draft"),
    ("disabled", "Disabled"),
    ("rejected", "Rejected"),
    ("in_review", "In Review"),
    ("published", "Published"),
)

RATING = (

    (1, "★☆☆☆☆"),
    (2, "★★☆☆☆"),
    (3, "★★★☆☆"),
    (4, "★★★★☆"),
    (5, "★★★★★"),

)

class Category(models.Model):
    cid = ShortUUIDField(unique=True, length=10, max_length=30, prefix="cat", alphabet="abcdefgh12345")
    title = models.CharField(max_length=400, default="Food")
    image = models.ImageField(upload_to="category", default="category.jpg")

    class Meta:
        verbose_name_plural = "Categories"

    def category_image(self):
        return mark_safe('<img src="%s" width="50" height="50" >' % (self.image.url))

    def __str__(self):
        return self.title

class Tags(models.Model):
    pass

class Vendor(models.Model):
    vid = ShortUUIDField(unique=True, length=10, max_length=30, prefix="ven", alphabet="abcdefgh12345")

    title = models.CharField(max_length=400, default="Nestify")
    image = models.ImageField(upload_to=user_directory_path, default="vendor.jpg")
    cover_image = models.ImageField(upload_to=user_directory_path, default="vendor.jpg")
    description = RichTextUploadingField(null=True, blank=True, default="I am an Amazing Vendor")


    address = models.CharField(max_length=300, default="123, Main Street.")
    contact = models.CharField(max_length=300, default="+123 (456) 789")
    chat_resp_time = models.CharField(max_length=300, default="100")
    shipping_on_time = models.CharField(max_length=300, default="100")
    authentic_rating = models.CharField(max_length=300, default="100")
    days_return = models.CharField(max_length=300, default="100")
    warranty_period = models.CharField(max_length=300, default="100")
    user =  models.ForeignKey(User, on_delete=models.SET_NULL, null=True )
    date = models.DateTimeField(auto_now_add=True, null=True, blank=True)




    class Meta:
        verbose_name_plural = "Vendor"

    def vendor_image(self):
        return mark_safe('<img src="%s" width="50" height="50" >' % (self.image.url))

    def __str__(self):
        return self.title

class Product(models.Model):
    pid = ShortUUIDField(unique=True, length=10, max_length=30, alphabet="abcdefgh12345")
    user =  models.ForeignKey(User, on_delete=models.SET_NULL, null=True )
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, related_name="category")
    vendor = models.ForeignKey(Vendor, on_delete=models.SET_NULL, null=True, related_name="product")

    title = models.CharField(max_length=300, default="Fresh Pear")
    image = models.ImageField(upload_to=user_directory_path, default="product.jpg")
    description = RichTextUploadingField(null=True, blank=True, default="This is the product")
    old_price = models.DecimalField(max_digits=9999999999, decimal_places=2, default="2.99")
    price = models.DecimalField(max_digits=9999999999, decimal_places=2, default="1.99")
    specification = RichTextUploadingField(null=True, blank=True)
    type = models.CharField(max_length=300, default="Organic", null=True, blank=True)
    stock_count = models.CharField(max_length=300, default="10", null=True, blank=True)
    life = models.CharField(max_length=300, default="100 Days", null=True, blank=True)
    mfd = models.DateTimeField(auto_now_add=False, null=True, blank=True)
    tags = TaggableManager(blank=True)


    # tags = models.ForeignKey(Tags, on_delete=models.SET_NULL, null=True )
    product_status = models.CharField(choices=STATUS, max_length=10, default="in_review")

    status = models.BooleanField(default=True)
    in_stock = models.BooleanField(default=True)
    featured = models.BooleanField(default=False)
    digital = models.BooleanField(default=True)
    sku = ShortUUIDField(unique=True, length=4, max_length=10, prefix="sku", alphabet="1234567890")
    date = models.DateTimeField(auto_now_add=True, null=True, blank=True)



    updated = models.DateTimeField(null=True, blank=True)

    class Meta:
        verbose_name_plural = "Products"

    def product_image(self):
        return mark_safe('<img src="%s" width="50" height="50" >' % (self.image.url))

    def __str__(self):
        return self.title

    def get_percentage(self):
        new_price = (self.price / self.old_price) * 100
        return new_price

class ProductImages(models.Model):
    images = models.ImageField(upload_to="product_images", default="product.jpg")
    product =  models.ForeignKey(Product, related_name="p_images", on_delete=models.SET_NULL, null=True)
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "Products Images"


########################## Cart, Order, OrderItems and Address ############################
########################## Cart, Order, OrderItems and Address ############################
########################## Cart, Order, OrderItems and Address ############################
########################## Cart, Order, OrderItems and Address ############################


class CartOrder(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)

    price = models.DecimalField(max_digits=9999999999, decimal_places=2, default="1.99")
    paid_status = models.BooleanField(default=False)
    order_date = models.DateTimeField(auto_now_add=True)
    product_status = models.CharField(choices=STATUS_CHOICE, max_length=30, default="processing")
    class Meta:
        verbose_name_plural = "Cart Order"





class CartOrderItems(models.Model):
    order = models.ForeignKey(CartOrder, on_delete=models.CASCADE)
    product_status = models.CharField(max_length=200)
    items = models.CharField(max_length=200)
    image = models.CharField(max_length=200)
    qty = models.IntegerField(default=0)
    price = models.DecimalField(max_digits=9999999999, decimal_places=2, default="1.99")
    total = models.DecimalField(max_digits=9999999999, decimal_places=2, default="1.99")
    invoice_no = models.CharField(max_length=200)

    class Meta:
        verbose_name_plural = "Cart Order Items"


    def order_img(self):
        return mark_safe('<img src="/media/%s" width="50" height="50" >' % (self.image))

########################## Product, Review, wishlists, and Address ############################
########################## Product, Review, wishlists, and Address ############################
########################## Product, Review, wishlists, and Address ############################
########################## Product, Review, wishlists, and Address ############################


class ProductReview(models.Model):
    user =  models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    product =  models.ForeignKey(Product, on_delete=models.SET_NULL, null=True, related_name='reviews')
    review = models.TextField()
    rating = models.IntegerField(choices=RATING, default=None)
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "Products Reviews"



    def __str__(self):
        return self.product.title

    def get_rating(self):
        return self.rating


class Wishlist (models.Model):
    user =  models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    product =  models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)

    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "wishlists"



    def __str__(self):
        return self.product.title

class Address(models.Model):

    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    address = models.CharField(max_length=100, null=True)
    status = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = "Address"

ecomprj/templates/useradmin/dashboard-add-products.html
{% extends 'useradmin/base.html' %}
{% load static %}
{% load humanize %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{{ form.media }}
{% block content %}   
<head>
    <style>
        select {
        appearance: none;
        outline: 0;
        background: rgba(240, 240, 240, 0.548);
        background-image: none;
        width: 100%;
        height: 700px;
        color: black;
        cursor: pointer;
        border: none;
        border-radius: 3px;
    }
     
    #id_category {
        position: relative;
        display: block;
        width: 15em;
        font-family: poppins;
        border: none;
        height: 3em;
        line-height: 3;
        overflow: hidden;
        border-radius: .25em;
        padding-bottom: 10px;
    }
    </style>
</head>
            <section class="content-main">
                <form method="POST" enctype="multipart/form-data">

                <div class="row">
                    <div class="col-9">
                        <div class="content-header">
                            <h2 class="content-title">Add New Product</h2>
                            <div>
                                <button class="btn btn-light rounded font-sm mr-5 text-body hover-up">Save to draft</button>
                                <button class="btn btn-md rounded font-sm hover-up">Publich</button>
                            </div>
                        </div>
                    </div>
                    
                    <div class="col-lg-6">
                        <div class="card mb-4">
                            <div class="card-header">
                                <h4>Basic</h4>
                            </div>
                            <div class="card-body">
                                
                                {% if form.errors %}
                                    
                                
                                <div class="alert alert-danger">
                                    <strong>{{ form.errors }}</strong>
                                </div>
                                {% endif %}
                                    {% csrf_token %}
                                    <div class="mb-4">
                                        <label for="product_name" class="form-label">Product title</label>
                                        {{form.title}}
                                        <!-- <input type="text" placeholder="Type here" class="form-control" id="product_name" /> -->
                                    </div>
                                    <div class="mb-4">
                                        <label class="form-label">Full description</label>
                                        {{form.description}}

                                        <!-- <textarea placeholder="Type here" class="form-control" rows="4"></textarea> -->
                                    </div>
                                    <div class="row">
                                        <div class="col-lg-4">
                                            <div class="mb-4">
                                                <label class="form-label">Selling price</label>
                                                <div class="row gx-2">
                                        {{form.price}}

                                                    <!-- <input placeholder="$" type="text" class="form-control" /> -->
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-lg-4">
                                            <div class="mb-4">
                                                <label class="form-label">Old price</label>
                                        {{form.old_price}}

                                                <!-- <input placeholder="$" type="text" class="form-control" /> -->
                                            </div>
                                        </div>
                                        <div class="col-lg-4">
                                            <label class="form-label">Currency</label>
                                            <select class="form-select">
                                                <option>USD</option>
                                               
                                            </select>
                                        </div>
                                    </div>
                                    <div class="mb-4">
                                        <label class="form-label">Type</label>
                                        {{form.type}}
                                        <!-- <input type="text" placeholder="%" class="form-control" id="product_name" /> -->
                                    </div>
                                    <div class="mb-4">
                                        <label class="form-label">Stock</label>
                                        {{form.stock_count}}
                                        <!-- <input type="text" placeholder="%" class="form-control" id="product_name" /> -->
                                    </div>

                                    <div class="mb-4">
                                        <label class="form-label">Life of Product</label>
                                        {{form.life}}
                                        <!-- <input type="text" placeholder="%" class="form-control" id="product_name" /> -->
                                    </div>

                                    <div class="mb-4">
                                        <label class="form-label">Manufactured Date</label>
                                        {{form.mfd}}
                                        <!-- <input type="text" placeholder="%" class="form-control" id="product_name" /> -->
                                    </div>

                                    <div class="mb-4">
                                        <label class="form-label">Tags</label>
                                        {{form.tags}}
                                        <small class="text-muted">Seperate tag using comma</small>
                                        <!-- <input type="text" placeholder="%" class="form-control" id="product_name" /> -->
                                    </div>

                                    <div class="mb-4">
                                        <label class="form-label">Digital Product</label>
                                        <br>
                                        {{form.digital}}
                                        <small class="text-muted">Check if only this is a digital product</small>
                                        <!-- <input type="text" placeholder="%" class="form-control" id="product_name" /> -->
                                    </div>
                                    
                                    <label class="form-check mb-4">
                                        <input class="form-check-input" type="checkbox" value="" />
                                        <span class="form-check-label"> Make a template </span>
                                    </label>
                            </div>
                        </div>
                        <!-- card end// -->
                       
                        <!-- card end// -->
                    </div>
                    <div class="col-lg-3">
                        <div class="card mb-4">
                            <div class="card-header">
                                <h4>Media</h4>
                            </div>
                            <div class="card-body">
                                <div class="input-upload">
                                    <img src="{% static 'assets2/imgs/theme/upload.svg' %}" alt="" />
                                    <!-- <input class="form-control" type="file" /> -->
                                    {{form.image}}
                                </div>
                            </div>
                        </div>
                        <!-- card end// -->
                        <div class="card mb-4">
                            <div class="card-header">
                                <h4>Others</h4>
                            </div>
                            <div class="card-body">
                                <div class="row gx-2">
                                    <div class="col-sm-6 mb-3">
                                        <label class="form-label">Category</label>
                                        {{form.category}}
                                    </div>
                                    
                                </div>
                                <!-- row.// -->
                            </div>
                            <br>
                            
                        </div>
                        <!-- card end// -->
                        <button class="btn mt-3 btn-md rounded font-sm hover-up" type="submit">Create Product</button>
                    </div>
                </div>
                </form>
            </section>
            <!-- content-main end// -->
              
            {% endblock content %}

ecomprj/templates/useradmin/dashboard-edit-products.html
{% extends 'useradmin/base.html' %}
{% load static %}
{% load humanize %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{{ form.media }}
{% block content %}   
<head>
    <style>
        select {
        appearance: none;
        outline: 0;
        background: rgba(240, 240, 240, 0.548);
        background-image: none;
        width: 100%;
        height: 700px;
        color: black;
        cursor: pointer;
        border: none;
        border-radius: 3px;
    }
     
    #id_category {
        position: relative;
        display: block;
        width: 15em;
        font-family: poppins;
        border: none;
        height: 3em;
        line-height: 3;
        overflow: hidden;
        border-radius: .25em;
        padding-bottom: 10px;
    }
    </style>
</head>
            <section class="content-main">
                <form method="POST" enctype="multipart/form-data">

                <div class="row">
                    <div class="col-9">
                        <div class="content-header">
                            <h2 class="content-title">Add New Product</h2>
                            <div>
                                <button class="btn btn-light rounded font-sm mr-5 text-body hover-up">Save to draft</button>
                                <button class="btn btn-md rounded font-sm hover-up">Publich</button>
                            </div>
                        </div>
                    </div>
                    
                    <div class="col-lg-6">
                        <div class="card mb-4">
                            <div class="card-header">
                                <h4>Basic</h4>
                            </div>
                            <div class="card-body">
                                
                                {% if form.errors %}
                                    
                                
                                <div class="alert alert-danger">
                                    <strong>{{ form.errors }}</strong>
                                </div>
                                {% endif %}
                                    {% csrf_token %}
                                    <div class="mb-4">
                                        <label for="product_name" class="form-label">Product title</label>
                                        {{form.title}}
                                        <!-- <input type="text" placeholder="Type here" class="form-control" id="product_name" /> -->
                                    </div>
                                    <div class="mb-4">
                                        <label class="form-label">Full description</label>
                                        {{form.description}}

                                        <!-- <textarea placeholder="Type here" class="form-control" rows="4"></textarea> -->
                                    </div>
                                    <div class="row">
                                        <div class="col-lg-4">
                                            <div class="mb-4">
                                                <label class="form-label">Selling price</label>
                                                <div class="row gx-2">
                                        {{form.price}}

                                                    <!-- <input placeholder="$" type="text" class="form-control" /> -->
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-lg-4">
                                            <div class="mb-4">
                                                <label class="form-label">Old price</label>
                                        {{form.old_price}}

                                                <!-- <input placeholder="$" type="text" class="form-control" /> -->
                                            </div>
                                        </div>
                                        <div class="col-lg-4">
                                            <label class="form-label">Currency</label>
                                            <select class="form-select">
                                                <option>USD</option>
                                               
                                            </select>
                                        </div>
                                    </div>
                                    <div class="mb-4">
                                        <label class="form-label">Type</label>
                                        {{form.type}}
                                        <!-- <input type="text" placeholder="%" class="form-control" id="product_name" /> -->
                                    </div>
                                    <div class="mb-4">
                                        <label class="form-label">Stock</label>
                                        {{form.stock_count}}
                                        <!-- <input type="text" placeholder="%" class="form-control" id="product_name" /> -->
                                    </div>

                                    <div class="mb-4">
                                        <label class="form-label">Life of Product</label>
                                        {{form.life}}
                                        <!-- <input type="text" placeholder="%" class="form-control" id="product_name" /> -->
                                    </div>

                                    <div class="mb-4">
                                        <label class="form-label">Manufactured Date</label>
                                        {{form.mfd}}
                                        <!-- <input type="text" placeholder="%" class="form-control" id="product_name" /> -->
                                    </div>

                                    <div class="mb-4">
                                        <label class="form-label">Tags</label>
                                        {{form.tags}}
                                        <small class="text-muted">Seperate tag using comma</small>
                                        <!-- <input type="text" placeholder="%" class="form-control" id="product_name" /> -->
                                    </div>

                                    <div class="mb-4">
                                        <label class="form-label">Digital Product</label>
                                        <br>
                                        {{form.digital}}
                                        <small class="text-muted">Check if only this is a digital product</small>
                                        <!-- <input type="text" placeholder="%" class="form-control" id="product_name" /> -->
                                    </div>
                                    
                                    <label class="form-check mb-4">
                                        <input class="form-check-input" type="checkbox" value="" />
                                        <span class="form-check-label"> Make a template </span>
                                    </label>
                            </div>
                        </div>
                        <!-- card end// -->
                       
                        <!-- card end// -->
                    </div>
                    <div class="col-lg-3">
                        <div class="card mb-4">
                            <div class="card-header">
                                <h4>Media</h4>
                            </div>
                            <div class="card-body">
                                <div class="input-upload">
                                    <img src="{{ product.image.url }}" alt="" />
                                    <!-- <input class="form-control" type="file" /> -->
                                    {{form.image}}
                                    
                                    
                                </div>
                            </div>
                        </div>
                        <!-- card end// -->
                        <div class="card mb-4">
                            <div class="card-header">
                                <h4>Others</h4>
                            </div>
                            <div class="card-body">
                                <div class="row gx-2">
                                    <div class="col-sm-6 mb-3">
                                        <label class="form-label">Category</label>
                                        {{form.category}}
                                    </div>
                                    
                                </div>
                                <!-- row.// -->
                            </div>
                            <br>
                            
                        </div>
                        <!-- card end// -->
                        <button class="btn mt-3 btn-md rounded font-sm hover-up" type="submit">Create Product</button>
                    </div>
                </div>
                </form>
            </section>
            <!-- content-main end// -->
              
            {% endblock content %}